SELECT [Id]
      ,[Dev_id]
      ,[Name]
      ,[Loc]
      ,[Coordx]
      ,[Coordy]
      ,[Ison]
      ,[Pm10_after]
      ,[Pm25_after]
      ,[State]
      ,[Timestamp]
      ,[Company_id]
      ,[Company_name]
  FROM [EMS].[dbo].[Dustsensor]
